apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-3tier-app2-api
  labels:
    app: node-3tier-app2-api
spec:
  selector:
    matchLabels:
      app: node-3tier-app2-api
  template:
    metadata:
      labels:
        app: node-3tier-app2-api
    spec:
      containers:
      - name: node-3tier-app2-api
        image: gbulanov/node-3tier-app2-api
        ports:
        - containerPort: 8080
        env:
          - name: PORT
            value: "8080"
          - name: DB
            valueFrom:
              secretKeyRef:
                name: db
                key: database
          - name: DBUSER
            valueFrom:
              secretKeyRef:
                name: db
                key: username
          - name: DBPASS
            valueFrom:
              secretKeyRef:
                name: db
                key: password
          - name: DBHOST
            value: localhost #SQL-agent from sidecar
          - name: DBPORT
            value: "5432"
        livenessProbe:
          httpGet:
            path: /
            port: 8080
        readinessProbe:
          httpGet:
            path: /
            port: 8080
        resources:
          limits:
            cpu: 100m
            memory: 256Mi
          requests:
            cpu: 80m
            memory: 128Mi

