---

apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: node-3tier-app2-web
  labels:
    app: node-3tier-app2-web
spec:
  minReplicas: 2
  maxReplicas: 6
  scaleTargetRef:
    apiVersion: argoproj.io/v1alpha1
    kind: Rollout
    name: node-3tier-app2-web
  targetCPUUtilizationPercentage: 80
